### ISSUE TITLE
Blob storage state

### ISSUE THREAD

**Issue by mud5150** [XpiritBV/Xpirit-Vsts-Release-Terraform#6]
Just getting started with integrating terraform into our CI workflow. Was glad to find your extension so thanks!

As I'm starting to work with this I have a few questions that could be me not understanding the process or perhaps they could be enhancements. I would be glad to put in pull requests for any of these if you agree with the concepts. 

Firstly I was wondering about the decision to "manually" handle the state with azure blob storage rather than use terraform's built in mechanism for using azure blob storage. 

For our projects we have the remote backend config in the repository in order to run plan locally. I expect this to conflict with the "manage state" option. I do really like that it allows you to use a service endpoint. One idea I had, since you're already using convention for the state file name, is you could potentially pass in the parameters to init to override what's in the repositories backend config with the tfs endpoint data. This would also have the benefit of the native locking that terraform provides. 

Let me know what you think. Thanks!

**Comment by pgroene** [comment]
I would probably manage the state my self out side of the task in a production environment. Just to be in control of that very important part of your terraform environment. At the moment I'm not in any project using terraforms, so I'm not totally up to date with the latest terraform versions and if there is anything changed since version 7. I would guess there are almost as many options on how to manage the state file as there are terraform project :), each project has its own best solution depending on the organization supporting it.

**Comment by mud5150** [comment]
Terraform now has good support, with locking, for using azure remote blob storage for tfstate. Would you be open to me putting in a pull request to change the "manage state with blobstorage" functionality with the behavior I proposed?

**Comment by pgroene** [comment]
Sure, I would be happy to get a pull request. Thanks for the effort!
